config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tweet-news', to: 'pages#tweet_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root to:  'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_navbar.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Michelle Gerber</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_masthead.html.erb
    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">My Blog</h1>
        <p class="lead blog-description">Time to write</p>
        <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
		<span>
			<%= link_to "Topics", topics_path %>
		</span>
      </div>
    </div>

app/views/shared/_blog_navbar.html.erb
<!-- ><nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
	 <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"         aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
      
	  <div class="container">
		  <%= link_to "Michelle Gerber", root_path, class: 'navbar-brand' %>
	  </div>
	  
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav mr-auto">
			  <%= nav_helper 'nav-link', 'li' %>
			   <%= login_helper 'nav-link' %>
		  </ul>
	  </div>
</nav> -->
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Michelle Gerber</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
    
    </nav>
</div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
	<div class="sidebar-module sidebar-module-inset">
		<h4>About</h4>
		<p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
	</div>
	
	<div class="sidebar-module">
		<h4>Topics</h4>
			<% @sidebar_topics.each do |topic| %>
			<p><%= link_to topic.title, topic_path(topic) %></p>
			<% end %>
	</div>
	
	<div class="sidebar-module">
		<h4>Elsewhere</h4>
		<ol class="list-unstyled">
			<li><%= fa_icon "github-alt" %></li>
			<li><%= fa_icon "twitter" %></li>
			<li><%= fa_icon "facebook" %></li>
		</ol>
	</div>
</div>

app/views/shared/_footer_application.html.erb
<div class="mastfoot">
	<div class="inner">
		<p class="app-footer"><%= copyright_generator %></p>
	</div>
</div>

app/views/shared/_footer_blog.html.erb
<footer class="blog-footer">
	<p class="app-footer"><%= copyright_generator %></p>
	<p>
		<a href="#">Back to top</a>
	</p>
</footer>

app/views/shared/_navbar.html.erb
<div class=" <%= location %>">
   <div><%= link_to "Home", root_path %></div>
   	<div><%= link_to "About", about_path %></div>
   	<div><%= link_to "Portfolio", portfolios_path %></div>
    <div><%= link_to "Contact", contact_path %></div>

</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
	<div class="container">
		<p class="float-right">
			<%= link_to "View All Portfolio Items", portfolios_path %>/
			<a href="#">Back to top</a>
		</p>
		<p><%= copyright_generator %></p>
	</div>
</footer>

app/views/shared/_portfolio_navbar.html.erb
<div class="masthead clearfix">
    <h3 class="masthead-brand">Michelle Gerber</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
    </nav>
 </div>
</div>